# View the docs https://docs.anyscale.com/reference/service-api#serviceconfig.

name: deploy-70b

# When empty, use the default image. This can be an Anyscale-provided base image
# like anyscale/ray:2.49.2-slim-py312-cu128, a user-provided base image (provided
# that it meets certain specs), or you can build new images using the Anyscale
# image builder at https://console.anyscale-staging.com/v2/container-images.

containerfile: ./Dockerfile

# Anyscale will auto-select the instance types, but you can also specify the instance
# types manually. Different GPU types are available on different clouds.
compute_config:
#   head_node:
#     instance_type: m5.2xlarge
#   worker_nodes:
#     # These instances are only available in AWS.
#     - instance_type: p4d.24xlarge
#       min_nodes: 0
#       max_nodes: 1
#       market_type: PREFER_SPOT # Defaults to ON_DEMAND
#     - instance_type: p4de.24xlarge
#       min_nodes: 0
#       max_nodes: 1
#       market_type: PREFER_SPOT # Defaults to ON_DEMAND
#     - instance_type: p5.48xlarge
#       min_nodes: 0
#       max_nodes: 1
#       market_type: PREFER_SPOT # Defaults to ON_DEMAND
#
#     # These instances are only available in GCP.
#     - instance_type: a2-highgpu-8g-nvidia-a100-40gb-8
#       market_type: PREFER_SPOT
#     - instance_type: a2-ultragpu-8g-nvidia-a100-80gb-8
#       market_type: PREFER_SPOT
#     - instance_type: a2-megagpu-16g-nvidia-a100-40gb-16
#       market_type: PREFER_SPOT
#     - instance_type: a3-highgpu-8g-nvidia-h100-80gb-8
#       market_type: PREFER_SPOT
#     - instance_type: a3-megagpu-8g-nvidia-h100-mega-80gb-8
#       market_type: PREFER_SPOT
#     - instance_type: a3-ultragpu-8g-nvidia-h200-141gb-8
#       market_type: PREFER_SPOT
  auto_select_worker_config: true

# Path to a local directory or a remote URI to a .zip file (S3, GS, HTTP) that
# will be the working directory for the job. The files in the directory will be
# automatically uploaded to the job environment in Anyscale.
working_dir: .

# When empty, this uses the default Anyscale Cloud in your organization.
cloud:

# Specify the Ray Serve app to deploy.
applications:
- import_path: serve:app
